// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context
{
    public partial class CvdAdminOperationlog
    {
        public int CoplogId { get; set; }
        public string CusrUsername { get; set; }
        public string CoplogOperation { get; set; }
        public string CoplogAppother { get; set; }
        public string CoplogAppother1 { get; set; }
        public string CoplogAppother2 { get; set; }
        public string CoplogAppother3 { get; set; }
        public string CoplogAppother4 { get; set; }
        public decimal? CoplogAppnumber { get; set; }
        public string CoplogCreatedby { get; set; }
        public DateTime CoplogCreatedon { get; set; }
        public string CoplogUpdatedby { get; set; }
        public DateTime CoplogUpdatedon { get; set; }
        public bool? CoplogDeletionstate { get; set; }
    }
}