// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context
{
    public partial class CvdBank
    {
        public int CbankId { get; set; }
        public string CcountryCode { get; set; }
        public string CbankCode { get; set; }
        public string CbankName { get; set; }
        public bool? CbankDeletionstate { get; set; }
    }
}