// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context
{
    public partial class CvdBanner
    {
        public int CbannerId { get; set; }
        public string CbannerTitle { get; set; }
        public string CbannerImages { get; set; }
        public string CbannerCreatedby { get; set; }
        public DateTime CbannerCreatedon { get; set; }
        public bool CbannerDeletionstate { get; set; }
    }
}