// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context
{
    public partial class CvdCountry
    {
        public int CcountryId { get; set; }
        public string CcountryCode { get; set; }
        public string CcountryCreatedby { get; set; }
        public DateTime CcountryCreatedon { get; set; }
        public string CcountryUpdatedby { get; set; }
        public DateTime CcountryUpdatedon { get; set; }
        public bool? CcountryDeletionstate { get; set; }
        public string CcountryMobilecode { get; set; }
        public string CcountryImagepath { get; set; }
        public string CcountryTaxLabel { get; set; }
        public decimal? CcountryTaxValue { get; set; }
        public string CcountryName { get; set; }
        public decimal? CcountryBuy { get; set; }
        public decimal? CcountrySell { get; set; }
    }
}