// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context
{
    public partial class CvdCashwalletlog
    {
        public int CcashId { get; set; }
        public string CusrUsername { get; set; }
        public decimal CcashCashin { get; set; }
        public decimal CcashCashout { get; set; }
        public string CcashCashname { get; set; }
        public decimal CcashWallet { get; set; }
        public string CcashAppuser { get; set; }
        public decimal? CcashAppnumber { get; set; }
        public decimal? CcashApprate { get; set; }
        public string CcashAppother { get; set; }
        public string CcashCreatedby { get; set; }
        public DateTime CcashCreatedon { get; set; }
        public bool CcashDeletionstate { get; set; }
        public int? CcashStatus { get; set; }
        public string CcashCardnumber { get; set; }
        public string CcashBranch { get; set; }
        public string CcashState { get; set; }
        public string CcashCity { get; set; }
        public string CcashBankname { get; set; }
        public string CcashBankaccountname { get; set; }
        public string CcashMobile { get; set; }
        public string CcashEmail { get; set; }
        public string CcashAddress { get; set; }
        public DateTime? CcashApprovaldate { get; set; }
        public string CcashPaymentmsg { get; set; }
        public string CcashPaymenttrandid { get; set; }
    }
}