// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context
{
    public partial class CvdCompanywallet
    {
        public int CcomId { get; set; }
        public string CcomName { get; set; }
        public string CcomNetworktype { get; set; }
        public bool CcomIsactive { get; set; }
        public string CcomWalletaddress { get; set; }
        public string CcomCreatedby { get; set; }
        public DateTime CcomCreatedon { get; set; }
        public bool CcomDeletionstate { get; set; }
    }
}