// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context.Models
{
    public partial class CvdDepositUsdt
    {
        public int CdepoId { get; set; }
        public string CusrUsername { get; set; }
        public decimal CdepoAmount { get; set; }
        public string CdepoTransactionId { get; set; }
        public string CdepoImagepath { get; set; }
        public string CdepoWalletAddress { get; set; }
        public string CdepoWalletNetwork { get; set; }
        public string CdepoWalletCompanyAddress { get; set; }
        public string CdepoWalletCompanyNetwork { get; set; }
        public int CdepoStatus { get; set; }
        public DateTime CdepoCreatedon { get; set; }
        public string CdepoUpdatedby { get; set; }
    }
}