// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context
{
    public partial class CvdDailytrans
    {
        public int CdailId { get; set; }
        public DateTime CdailTrandate { get; set; }
        public decimal? CdailRecharge { get; set; }
        public decimal? CdailBet { get; set; }
        public decimal? CdailWin { get; set; }
        public decimal? CdailWithdraw { get; set; }
    }
}