// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context
{ 
    public partial class CvdExchangerate
    {
        public int CexchangeId { get; set; }
        public string CexchangeCode { get; set; }        
        public decimal? CexchangeBuy { get; set; }
        public decimal? CexchangeSell { get; set; }
        public bool? CexchangeDeletionstate { get; set; }
    }
}