// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context.Models
{
    public partial class CvdGameSession
    {
        public int CgamesesId { get; set; }
        public int CgameId { get; set; }
        public string CgamePeriod { get; set; }
        public int CgameResult { get; set; }
        public DateTime CgameStart { get; set; }
        public DateTime CgameEnd { get; set; }
        public int CgameStatus { get; set; }
        public bool CgamesesDeletionstate { get; set; }
    }
}