// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context.Models
{
    public partial class CvdGameSessionBet
    {
        public int CbetId { get; set; }
        public int CgamesesId { get; set; }
        public int CgameNumber { get; set; }
        public string CusrUsername { get; set; }
        public decimal CgameAmount { get; set; }
        public decimal CgameWinAmount { get; set; }
        public bool CbetDeletionstate { get; set; }
        public int? CgameId { get; set; }
    }
}