// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context.Models
{
    public partial class CvdGame
    {
        public int CgameId { get; set; }
        public string CgameName { get; set; }
        public int CgameStatus { get; set; }
        public string CgameImagepath { get; set; }
        public int CgameType { get; set; }
        public int CgameDurationSeconds { get; set; }
        public decimal CgameNo9Return { get; set; }
        public decimal CgameNo8Return { get; set; }
        public decimal CgameNo7Return { get; set; }
        public decimal CgameNo6Return { get; set; }
        public decimal CgameNo5Return { get; set; }
        public decimal CgameNo4Return { get; set; }
        public decimal CgameNo3Return { get; set; }
        public decimal CgameNo2Return { get; set; }
        public decimal CgameNo1Return { get; set; }
        public decimal CgameNo0Return { get; set; }
        public decimal CgameRedReturn { get; set; }
        public decimal CgameVioletReturn { get; set; }
        public decimal CgameRed0Return { get; set; }
        public decimal CgameGreenReturn { get; set; }
        public decimal CgameGreen5Return { get; set; }
        public bool CgameDeletionstate { get; set; }
    }
}