// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context
{
    public partial class CvdMemberBank
    {
        public int CbankId { get; set; }
        public string CusrUsername { get; set; }
        public string CbankName { get; set; }
        public string CbankIfsccode { get; set; }
        public string CbankBankaccountname { get; set; }
        public string CbankBankaccount { get; set; }
        public string CbankState { get; set; }
        public string CbankCity { get; set; }
        public string CbankAddress { get; set; }
        public string CbankMobile { get; set; }
        public string CbankEmail { get; set; }
        public string CbankCreatedby { get; set; }
        public DateTime CbankCreatedon { get; set; }
        public bool CbankDeletionstate { get; set; }
    }
}