// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context
{
    public partial class CvdOtp
    {
        public int CotpId { get; set; }
        public string CotpCode { get; set; }
        public string CusrUsername { get; set; }
        public string CotpCreatedby { get; set; }
        public DateTime CotpCreatedon { get; set; }
        public string CotpUpdatedby { get; set; }
        public DateTime CotpUpdatedon { get; set; }
        public bool? CotpDeletionstate { get; set; }
    }
}