// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context
{
    public partial class CvdPaymentinfo
    {
        public int CpaymentId { get; set; }
        public string CusrUsername { get; set; }
        public string CpaymentTranspaymentid { get; set; }
        public string CpaymentTransid { get; set; }
        public decimal CpaymentAmount { get; set; }
        public string CpaymentIssuebank { get; set; }
        public string CpaymentTransmsg { get; set; }
        public string CpaymentReturncode { get; set; }
        public string CpaymentReturnsign { get; set; }
        public DateTime CpaymentCreatedon { get; set; }
    }
}