// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context
{
    public partial class CvdProduct
    {
        public int CproId { get; set; }
        public string CproTitle { get; set; }
        public string CproImages { get; set; }
        public string CproDesc { get; set; }
        public string CproDescAdd { get; set; }
        public decimal CproPrice { get; set; }
        public string CproCreatedby { get; set; }
        public DateTime CproCreatedon { get; set; }
        public bool CproDeletionstate { get; set; }
    }
}