// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context
{
    public partial class CvdParameter
    {
        public int CparaId { get; set; }
        public string CparaName { get; set; }
        public string CparaDescription { get; set; }
        public string CparaUom { get; set; }
        public string CparaStringvalue { get; set; }
        public decimal CparaDecimalvalue { get; set; }
        public string CparaCreatedby { get; set; }
        public DateTime CparaCreatedon { get; set; }
        public string CparaUpdatedby { get; set; }
        public DateTime CparaUpdatedon { get; set; }
        public bool? CparaDeletionstate { get; set; }
    }
}