// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context.Models
{
    public partial class CvdRedPacket
    {
        public int CredpId { get; set; }
        public string CredpReferenceId { get; set; }
        public string CredpAgent { get; set; }
        public string CusrUsername { get; set; }
        public decimal CredpAmount { get; set; }
        public DateTime CredpCreatedon { get; set; }
        public DateTime? CredpClaimedon { get; set; }
        public int CredpStatus { get; set; }
        public bool CredpDeletionstate { get; set; }
    }
}