// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context
{
    public partial class CvdReceipt
    {
        public int CrecId { get; set; }
        public string CusrUsername { get; set; }
        public string CrecFolder { get; set; }
        public string CrecImagepath { get; set; }
        public string CrecCategory { get; set; }
        public DateTime CrecDate { get; set; }
        public DateTime CrecCreatedon { get; set; }
        public bool CrecDeletionstate { get; set; }
    }
}