// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context
{
    public partial class CvdSystemerror
    {
        public int CerrorId { get; set; }
        public string CerrorInfo { get; set; }
        public string CerrorAppother { get; set; }
        public string CerrorAppother2 { get; set; }
        public string CerrorAppother3 { get; set; }
        public DateTime CerrorCreatedon { get; set; }
    }
}