// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Entity.Context.Models
{
    public partial class CvdUserInfo
    {
        public int CusrId { get; set; }
        public string CusrUsername { get; set; }
        public string MemberWalletAddress { get; set; }
        public string MemberWalletNetwork { get; set; }
    }
}