Use ColorPrediction

ALTER TABLE [dbo].[CVD_GAME_SESSION]
ADD CGAME_TOTAL_BET DECIMAL(15,2) DEFAULT 0
GO

ALTER TABLE [dbo].[CVD_GAME_SESSION]
ADD CGAME_TOTAL_WIN DECIMAL(15,2) DEFAULT 0
GO

UPDATE [dbo].[CVD_GAME_SESSION]
SET CGAME_TOTAL_BET = 0, CGAME_TOTAL_WIN = 0