Use ColorPrediction

ALTER TABLE [dbo].CVD_GAME_SESSION_BET
ADD [CGAME_ID] INT DEFAULT 0
GO

UPDATE [dbo].CVD_GAME_SESSION_BET
SET [CGAME_ID] = 0

ALTER TABLE [dbo].CVD_GAME_SESSION_BET
ADD [CGAME_PERIOD] NVARCHAR(200) DEFAULT ''
GO

UPDATE [dbo].CVD_GAME_SESSION_BET
SET [CGAME_PERIOD] = ''
