INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('WithdrawalMinAmount', 'Withdrawal Minimum Amount', 'DECIMAL', '', 10.00, 'SYS', 'SYS')

INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('WithdrawalMaxAmount', 'Withdrawal Maximum Amount', 'DECIMAL', '', 10.00, 'SYS', 'SYS')

INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('WithdrawalServiceFee', 'Withdrawal Service Fee', 'DECIMAL', '', 10.00, 'SYS', 'SYS')

INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('FirstChargeLevel1', 'First Charge % for Level 1(Based on Commission)', 'DECIMAL', '', 10.00, 'SYS', 'SYS')

INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('FirstChargeLevel2', 'First Charge % for Level 2(Based on Commission)', 'DECIMAL', '', 10.00, 'SYS', 'SYS')



INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('RechargeMinAmount', 'Recharge Minimum Amount', 'DECIMAL', '', 10.00, 'SYS', 'SYS')

INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('RechargeMaxAmount', 'Recharge Maximum Amount', 'DECIMAL', '', 10.00, 'SYS', 'SYS')


INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('WinningLevel1', 'Winning % for Level 1(Based on Commission)', 'DECIMAL', '', 10.00, 'SYS', 'SYS')

INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('WinningLevel1', 'Winning % for Level 2(Based on Commission)', 'DECIMAL', '', 10.00, 'SYS', 'SYS')

INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('GameServiceFee', 'Game Service Fee', 'DECIMAL', '', 10.00, 'SYS', 'SYS')

INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('GameHandlingFee', 'Game Handling Fee', 'DECIMAL', '', 10.00, 'SYS', 'SYS')

INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('SponsorBonusLevel1', 'Sponsor Bonus % for Level 1(Based on Commission)', 'DECIMAL', '', 10.00, 'SYS', 'SYS')

INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('SponsorBonusLevel2', 'Sponsor Bonus % for Level 2(Based on Commission)', 'DECIMAL', '', 10.00, 'SYS', 'SYS')

INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('SponsorBonusLevel3', 'Sponsor Bonus % for Level 3(Based on Commission)', 'DECIMAL', '', 10.00, 'SYS', 'SYS')


INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('CoinWithdrawalCharges', 'Coin Withdrawal Charges', 'DECIMAL', '', 10.00, 'SYS', 'SYS')

INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('CoinMinWithdrawal', 'Coin Minimum Amount', 'DECIMAL', '', 10.00, 'SYS', 'SYS')

INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('CoinMaxWithdrawal', 'Coin Maximum Amount', 'DECIMAL', '', 10.00, 'SYS', 'SYS')


INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('GatewayPaymentHost', 'Gateway Payment Host', 'STRING', 'https://cspay.link/Pay_Index.html', 0, 'SYS', 'SYS')

INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('GatewayWithdrawalHost', 'Gateway Withdrawal Host', 'STRING', 'https://cspay.link/Payment_Dfpay_add.html', 0, 'SYS', 'SYS')

INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('GatewayMemberID', 'Gateway Member ID', 'STRING', '10306', 0, 'SYS', 'SYS')

INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('GatewayPaymentKey', 'Gateway Payment Key', 'STRING', '', 0, 'SYS', 'SYS')


INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('SupportPhoneNumber', 'Support Phone Number', 'STRING', 'https://t.me/vip1huat365com', 0, 'SYS', 'SYS')

INSERT INTO [dbo].[CVD_PARAMETER] ([CPARA_NAME], [CPARA_DESCRIPTION], [CPARA_UOM], [CPARA_STRINGVALUE], [CPARA_DECIMALVALUE], [CPARA_CREATEDBY], [CPARA_UPDATEDBY])
VALUES ('SupportApkUrl', 'Support Apk Url', 'STRING', 'https://tinyurl.com/4uxjevst', 0, 'SYS', 'SYS')
