//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PackBuddyShared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PackBuddyShared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreshMVC.Resources.PackBuddyShared", typeof(PackBuddyShared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string btnLogIn {
            get {
                return ResourceManager.GetString("btnLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request OTP.
        /// </summary>
        public static string btnRequestOTP {
            get {
                return ResourceManager.GetString("btnRequestOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string btnSignUp {
            get {
                return ResourceManager.GetString("btnSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string btnView {
            get {
                return ResourceManager.GetString("btnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string lblAboutPackBuddy {
            get {
                return ResourceManager.GetString("lblAboutPackBuddy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string lblActive {
            get {
                return ResourceManager.GetString("lblActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin account exists.
        /// </summary>
        public static string lblAdminAccExists {
            get {
                return ResourceManager.GetString("lblAdminAccExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string lblAgent {
            get {
                return ResourceManager.GetString("lblAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string lblAmount {
            get {
                return ResourceManager.GetString("lblAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beast.
        /// </summary>
        public static string lblBeast {
            get {
                return ResourceManager.GetString("lblBeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty.
        /// </summary>
        public static string lblBeauty {
            get {
                return ResourceManager.GetString("lblBeauty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string lblBlock {
            get {
                return ResourceManager.GetString("lblBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Wallet.
        /// </summary>
        public static string lblCashWallet {
            get {
                return ResourceManager.GetString("lblCashWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string lblChangePassword {
            get {
                return ResourceManager.GetString("lblChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimed On.
        /// </summary>
        public static string lblClaimedOn {
            get {
                return ResourceManager.GetString("lblClaimedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string lblConfirmNewPass {
            get {
                return ResourceManager.GetString("lblConfirmNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password is required.
        /// </summary>
        public static string lblConfirmNewPasswordIsRequired {
            get {
                return ResourceManager.GetString("lblConfirmNewPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string lblCopyrightz {
            get {
                return ResourceManager.GetString("lblCopyrightz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string lblCreatedOn {
            get {
                return ResourceManager.GetString("lblCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is required.
        /// </summary>
        public static string lblCurrentPasswordIsRequired {
            get {
                return ResourceManager.GetString("lblCurrentPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password does not match.
        /// </summary>
        public static string lblCurrentPasswordNotMatch {
            get {
                return ResourceManager.GetString("lblCurrentPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string lblCurrPwd {
            get {
                return ResourceManager.GetString("lblCurrPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string lblDuration {
            get {
                return ResourceManager.GetString("lblDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string lblFailed {
            get {
                return ResourceManager.GetString("lblFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        public static string lblForgetPassword {
            get {
                return ResourceManager.GetString("lblForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green 5 return rate.
        /// </summary>
        public static string lblGreen5Return {
            get {
                return ResourceManager.GetString("lblGreen5Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green return rate.
        /// </summary>
        public static string lblGreenReturn {
            get {
                return ResourceManager.GetString("lblGreenReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string lblInActive {
            get {
                return ResourceManager.GetString("lblInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro.
        /// </summary>
        public static string lblIntro {
            get {
                return ResourceManager.GetString("lblIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro Code.
        /// </summary>
        public static string lblIntroCode {
            get {
                return ResourceManager.GetString("lblIntroCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username.
        /// </summary>
        public static string lblInvalidUsername {
            get {
                return ResourceManager.GetString("lblInvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string lblLogOut {
            get {
                return ResourceManager.GetString("lblLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string lblMember {
            get {
                return ResourceManager.GetString("lblMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Type.
        /// </summary>
        public static string lblMemberType {
            get {
                return ResourceManager.GetString("lblMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string lblNameIsRequired {
            get {
                return ResourceManager.GetString("lblNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required.
        /// </summary>
        public static string lblNewPasswordIsRequired {
            get {
                return ResourceManager.GetString("lblNewPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string lblNewPwd {
            get {
                return ResourceManager.GetString("lblNewPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found.
        /// </summary>
        public static string lblNoRecFound {
            get {
                return ResourceManager.GetString("lblNoRecFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Used.
        /// </summary>
        public static string lblNotUsed {
            get {
                return ResourceManager.GetString("lblNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 0 return rate.
        /// </summary>
        public static string lblNumber0ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber0ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 1 return rate.
        /// </summary>
        public static string lblNumber1ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber1ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 2 return rate.
        /// </summary>
        public static string lblNumber2ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber2ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 3 return rate.
        /// </summary>
        public static string lblNumber3ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber3ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 4 return rate.
        /// </summary>
        public static string lblNumber4ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber4ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 5 return rate.
        /// </summary>
        public static string lblNumber5ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber5ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 6 return rate.
        /// </summary>
        public static string lblNumber6ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber6ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 7 return rate.
        /// </summary>
        public static string lblNumber7ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber7ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 8 return rate.
        /// </summary>
        public static string lblNumber8ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber8ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 9 return rate.
        /// </summary>
        public static string lblNumber9ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber9ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match.
        /// </summary>
        public static string lblPassNotMatch {
            get {
                return ResourceManager.GetString("lblPassNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string lblPasswordIsRequired {
            get {
                return ResourceManager.GetString("lblPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is required.
        /// </summary>
        public static string lblPhoneIsRequired {
            get {
                return ResourceManager.GetString("lblPhoneIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        public static string lblPleaseWait {
            get {
                return ResourceManager.GetString("lblPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recharge Wallet.
        /// </summary>
        public static string lblRechargeWallet {
            get {
                return ResourceManager.GetString("lblRechargeWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red 0 return rate.
        /// </summary>
        public static string lblRed0Return {
            get {
                return ResourceManager.GetString("lblRed0Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red return rate.
        /// </summary>
        public static string lblRedReturn {
            get {
                return ResourceManager.GetString("lblRedReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference ID.
        /// </summary>
        public static string lblReferenceID {
            get {
                return ResourceManager.GetString("lblReferenceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string lblRememberMe {
            get {
                return ResourceManager.GetString("lblRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Password.
        /// </summary>
        public static string lblShowPassword {
            get {
                return ResourceManager.GetString("lblShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string lblUpdate {
            get {
                return ResourceManager.GetString("lblUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string lblUsed {
            get {
                return ResourceManager.GetString("lblUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string lblUsernameIsRequired {
            get {
                return ResourceManager.GetString("lblUsernameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string lblVerificationCode {
            get {
                return ResourceManager.GetString("lblVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string lblView {
            get {
                return ResourceManager.GetString("lblView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet return rate.
        /// </summary>
        public static string lblVioletReturn {
            get {
                return ResourceManager.GetString("lblVioletReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string lblWarning {
            get {
                return ResourceManager.GetString("lblWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string mnuAdmin {
            get {
                return ResourceManager.GetString("mnuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Listing.
        /// </summary>
        public static string mnuAdminListing {
            get {
                return ResourceManager.GetString("mnuAdminListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string mnuGame {
            get {
                return ResourceManager.GetString("mnuGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing.
        /// </summary>
        public static string mnuListing {
            get {
                return ResourceManager.GetString("mnuListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Packet.
        /// </summary>
        public static string mnuRedPacket {
            get {
                return ResourceManager.GetString("mnuRedPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string mnuUser {
            get {
                return ResourceManager.GetString("mnuUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Listing.
        /// </summary>
        public static string mnuUserListing {
            get {
                return ResourceManager.GetString("mnuUserListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimed successfully.
        /// </summary>
        public static string msgClaimSuccessfully {
            get {
                return ResourceManager.GetString("msgClaimSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        public static string msgConfirmDelete {
            get {
                return ResourceManager.GetString("msgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration must be longer than 60 seconds.
        /// </summary>
        public static string msgDurationMustBeLongerThan60Seconds {
            get {
                return ResourceManager.GetString("msgDurationMustBeLongerThan60Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You balance is insufficient.
        /// </summary>
        public static string msgGameInsufficientFund {
            get {
                return ResourceManager.GetString("msgGameInsufficientFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session not found.
        /// </summary>
        public static string msgGameSessionNotFound {
            get {
                return ResourceManager.GetString("msgGameSessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re too late to place a bet on this. Please wait for next session.
        /// </summary>
        public static string msgGameTooLateToBet {
            get {
                return ResourceManager.GetString("msgGameTooLateToBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input amount for this red packet.
        /// </summary>
        public static string msgInputAmountRedPacket {
            get {
                return ResourceManager.GetString("msgInputAmountRedPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient wallet balance.
        /// </summary>
        public static string msgInsufficientWalletBalance {
            get {
                return ResourceManager.GetString("msgInsufficientWalletBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login.
        /// </summary>
        public static string msgInvalidLogin {
            get {
                return ResourceManager.GetString("msgInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name.
        /// </summary>
        public static string msgInvalidName {
            get {
                return ResourceManager.GetString("msgInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string msgInvalidPassword {
            get {
                return ResourceManager.GetString("msgInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidPhoneNumber.
        /// </summary>
        public static string msgInvalidPhoneNumber {
            get {
                return ResourceManager.GetString("msgInvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid red packet.
        /// </summary>
        public static string msgInvalidRedPacket {
            get {
                return ResourceManager.GetString("msgInvalidRedPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid referral.
        /// </summary>
        public static string msgInvalidReferral {
            get {
                return ResourceManager.GetString("msgInvalidReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password do not match.
        /// </summary>
        public static string msgPasswordNotMatch {
            get {
                return ResourceManager.GetString("msgPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is not registered.
        /// </summary>
        public static string msgPhoneIsNotRegistered {
            get {
                return ResourceManager.GetString("msgPhoneIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successfully.
        /// </summary>
        public static string msgSaveSuccessfully {
            get {
                return ResourceManager.GetString("msgSaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired.
        /// </summary>
        public static string msgSessionExpired {
            get {
                return ResourceManager.GetString("msgSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Existed.
        /// </summary>
        public static string msgUserExisted {
            get {
                return ResourceManager.GetString("msgUserExisted", resourceCulture);
            }
        }
    }
}
