//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PackBuddyShared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PackBuddyShared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreshMVC.Resources.PackBuddyShared", typeof(PackBuddyShared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string btnDownload {
            get {
                return ResourceManager.GetString("btnDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string btnLogIn {
            get {
                return ResourceManager.GetString("btnLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string btnNext {
            get {
                return ResourceManager.GetString("btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request OTP.
        /// </summary>
        public static string btnRequestOTP {
            get {
                return ResourceManager.GetString("btnRequestOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string btnSignUp {
            get {
                return ResourceManager.GetString("btnSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string btnView {
            get {
                return ResourceManager.GetString("btnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string lblAboutPackBuddy {
            get {
                return ResourceManager.GetString("lblAboutPackBuddy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string lblAction {
            get {
                return ResourceManager.GetString("lblAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string lblActive {
            get {
                return ResourceManager.GetString("lblActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Name.
        /// </summary>
        public static string lblActualName {
            get {
                return ResourceManager.GetString("lblActualName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bank Card.
        /// </summary>
        public static string lblAddBankCard {
            get {
                return ResourceManager.GetString("lblAddBankCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin account exists.
        /// </summary>
        public static string lblAdminAccExists {
            get {
                return ResourceManager.GetString("lblAdminAccExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string lblAgent {
            get {
                return ResourceManager.GetString("lblAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string lblAll {
            get {
                return ResourceManager.GetString("lblAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string lblAmount {
            get {
                return ResourceManager.GetString("lblAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apk Url.
        /// </summary>
        public static string lblApkUrl {
            get {
                return ResourceManager.GetString("lblApkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apk Url is Required.
        /// </summary>
        public static string lblApkUrlIsRequired {
            get {
                return ResourceManager.GetString("lblApkUrlIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Time.
        /// </summary>
        public static string lblApplicationTime {
            get {
                return ResourceManager.GetString("lblApplicationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string lblApprove {
            get {
                return ResourceManager.GetString("lblApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Balance.
        /// </summary>
        public static string lblAvailableBalance {
            get {
                return ResourceManager.GetString("lblAvailableBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Red Packet Balance.
        /// </summary>
        public static string lblAvailRedPacketBalance {
            get {
                return ResourceManager.GetString("lblAvailRedPacketBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string lblBalance {
            get {
                return ResourceManager.GetString("lblBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance after withdrawal.
        /// </summary>
        public static string lblBalanceAfterWith {
            get {
                return ResourceManager.GetString("lblBalanceAfterWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance before withdrawal.
        /// </summary>
        public static string lblBalanceBeforeWith {
            get {
                return ResourceManager.GetString("lblBalanceBeforeWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        public static string lblBankAccount {
            get {
                return ResourceManager.GetString("lblBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank card.
        /// </summary>
        public static string lblBankcard {
            get {
                return ResourceManager.GetString("lblBankcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Info - HotMall.
        /// </summary>
        public static string lblBankInfoHotmall {
            get {
                return ResourceManager.GetString("lblBankInfoHotmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string lblBankName {
            get {
                return ResourceManager.GetString("lblBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beast.
        /// </summary>
        public static string lblBeast {
            get {
                return ResourceManager.GetString("lblBeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty.
        /// </summary>
        public static string lblBeauty {
            get {
                return ResourceManager.GetString("lblBeauty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bet Amount.
        /// </summary>
        public static string lblBetAmount {
            get {
                return ResourceManager.GetString("lblBetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string lblBlock {
            get {
                return ResourceManager.GetString("lblBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Rate.
        /// </summary>
        public static string lblBuy {
            get {
                return ResourceManager.GetString("lblBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Rate is required.
        /// </summary>
        public static string lblBuyRateIsRequired {
            get {
                return ResourceManager.GetString("lblBuyRateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash In.
        /// </summary>
        public static string lblCashIn {
            get {
                return ResourceManager.GetString("lblCashIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Name.
        /// </summary>
        public static string lblCashName {
            get {
                return ResourceManager.GetString("lblCashName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Out.
        /// </summary>
        public static string lblCashOut {
            get {
                return ResourceManager.GetString("lblCashOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Wallet.
        /// </summary>
        public static string lblCashWallet {
            get {
                return ResourceManager.GetString("lblCashWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string lblChangePassword {
            get {
                return ResourceManager.GetString("lblChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimed On.
        /// </summary>
        public static string lblClaimedOn {
            get {
                return ResourceManager.GetString("lblClaimedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string lblClose {
            get {
                return ResourceManager.GetString("lblClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USDT Withdrawal Charges.
        /// </summary>
        public static string lblCoinWithdrawalCharges {
            get {
                return ResourceManager.GetString("lblCoinWithdrawalCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string lblCompleted {
            get {
                return ResourceManager.GetString("lblCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string lblConfirm {
            get {
                return ResourceManager.GetString("lblConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string lblConfirmNewPass {
            get {
                return ResourceManager.GetString("lblConfirmNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password is required.
        /// </summary>
        public static string lblConfirmNewPasswordIsRequired {
            get {
                return ResourceManager.GetString("lblConfirmNewPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string lblCopyrightz {
            get {
                return ResourceManager.GetString("lblCopyrightz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string lblCountryCode {
            get {
                return ResourceManager.GetString("lblCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code is required.
        /// </summary>
        public static string lblCountryCodeIsRequired {
            get {
                return ResourceManager.GetString("lblCountryCodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name.
        /// </summary>
        public static string lblCountryName {
            get {
                return ResourceManager.GetString("lblCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name is required.
        /// </summary>
        public static string lblCountryNameIsRequired {
            get {
                return ResourceManager.GetString("lblCountryNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string lblCreatedOn {
            get {
                return ResourceManager.GetString("lblCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Balance.
        /// </summary>
        public static string lblCurrentBalance {
            get {
                return ResourceManager.GetString("lblCurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is required.
        /// </summary>
        public static string lblCurrentPasswordIsRequired {
            get {
                return ResourceManager.GetString("lblCurrentPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password does not match.
        /// </summary>
        public static string lblCurrentPasswordNotMatch {
            get {
                return ResourceManager.GetString("lblCurrentPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string lblCurrPwd {
            get {
                return ResourceManager.GetString("lblCurrPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal.
        /// </summary>
        public static string lblDeal {
            get {
                return ResourceManager.GetString("lblDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduct.
        /// </summary>
        public static string lblDeduct {
            get {
                return ResourceManager.GetString("lblDeduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string lblDeleteSuccessfully {
            get {
                return ResourceManager.GetString("lblDeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string lblDuration {
            get {
                return ResourceManager.GetString("lblDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string lblEnd {
            get {
                return ResourceManager.GetString("lblEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethereum.
        /// </summary>
        public static string lblEtherum {
            get {
                return ResourceManager.GetString("lblEtherum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Info.
        /// </summary>
        public static string lblExtraInfo {
            get {
                return ResourceManager.GetString("lblExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string lblFailed {
            get {
                return ResourceManager.GetString("lblFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifth Level.
        /// </summary>
        public static string lblFifthLevel {
            get {
                return ResourceManager.GetString("lblFifthLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Option.
        /// </summary>
        public static string lblFilterOption {
            get {
                return ResourceManager.GetString("lblFilterOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Amount.
        /// </summary>
        public static string lblFinalAmount {
            get {
                return ResourceManager.GetString("lblFinalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Charge.
        /// </summary>
        public static string lblFirstCharge {
            get {
                return ResourceManager.GetString("lblFirstCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Level.
        /// </summary>
        public static string lblFirstLevel {
            get {
                return ResourceManager.GetString("lblFirstLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Level Commission.
        /// </summary>
        public static string lblFirstLevelCommisison {
            get {
                return ResourceManager.GetString("lblFirstLevelCommisison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        public static string lblForgetPassword {
            get {
                return ResourceManager.GetString("lblForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth Level.
        /// </summary>
        public static string lblFourthLevel {
            get {
                return ResourceManager.GetString("lblFourthLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string lblFrom {
            get {
                return ResourceManager.GetString("lblFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Fees.
        /// </summary>
        public static string lblGameFees {
            get {
                return ResourceManager.GetString("lblGameFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give All This Level.
        /// </summary>
        public static string lblGiveAllThisLevel {
            get {
                return ResourceManager.GetString("lblGiveAllThisLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give red packet.
        /// </summary>
        public static string lblGiveRedPacket {
            get {
                return ResourceManager.GetString("lblGiveRedPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green 5 return rate.
        /// </summary>
        public static string lblGreen5Return {
            get {
                return ResourceManager.GetString("lblGreen5Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green return rate.
        /// </summary>
        public static string lblGreenReturn {
            get {
                return ResourceManager.GetString("lblGreenReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling Fee.
        /// </summary>
        public static string lblHandlingFee {
            get {
                return ResourceManager.GetString("lblHandlingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string lblHome {
            get {
                return ResourceManager.GetString("lblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFSC Code.
        /// </summary>
        public static string lblIFSCCode {
            get {
                return ResourceManager.GetString("lblIFSCCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string lblInActive {
            get {
                return ResourceManager.GetString("lblInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string lblInfo {
            get {
                return ResourceManager.GetString("lblInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string lblInProgress {
            get {
                return ResourceManager.GetString("lblInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro.
        /// </summary>
        public static string lblIntro {
            get {
                return ResourceManager.GetString("lblIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro Code.
        /// </summary>
        public static string lblIntroCode {
            get {
                return ResourceManager.GetString("lblIntroCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Amount.
        /// </summary>
        public static string lblInvalidAmount {
            get {
                return ResourceManager.GetString("lblInvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Bank Account.
        /// </summary>
        public static string lblInvalidBankAccount {
            get {
                return ResourceManager.GetString("lblInvalidBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string lblInvalidEmail {
            get {
                return ResourceManager.GetString("lblInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Picture.
        /// </summary>
        public static string lblInvalidImage {
            get {
                return ResourceManager.GetString("lblInvalidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mobile.
        /// </summary>
        public static string lblInvalidMobile {
            get {
                return ResourceManager.GetString("lblInvalidMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Title.
        /// </summary>
        public static string lblInvalidTitle {
            get {
                return ResourceManager.GetString("lblInvalidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username.
        /// </summary>
        public static string lblInvalidUsername {
            get {
                return ResourceManager.GetString("lblInvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string lblIsActive {
            get {
                return ResourceManager.GetString("lblIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Green.
        /// </summary>
        public static string lblJoinGreen {
            get {
                return ResourceManager.GetString("lblJoinGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Red.
        /// </summary>
        public static string lblJoinRed {
            get {
                return ResourceManager.GetString("lblJoinRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Violet.
        /// </summary>
        public static string lblJoinViolet {
            get {
                return ResourceManager.GetString("lblJoinViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string lblLogOut {
            get {
                return ResourceManager.GetString("lblLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Approve.
        /// </summary>
        public static string lblManualApprove {
            get {
                return ResourceManager.GetString("lblManualApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Amount.
        /// </summary>
        public static string lblMaxAmount {
            get {
                return ResourceManager.GetString("lblMaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum for recharge:.
        /// </summary>
        public static string lblMaxRecharge {
            get {
                return ResourceManager.GetString("lblMaxRecharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string lblMember {
            get {
                return ResourceManager.GetString("lblMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ID.
        /// </summary>
        public static string lblMemberID {
            get {
                return ResourceManager.GetString("lblMemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ID is Required.
        /// </summary>
        public static string lblMemberIDIsRequired {
            get {
                return ResourceManager.GetString("lblMemberIDIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Type.
        /// </summary>
        public static string lblMemberType {
            get {
                return ResourceManager.GetString("lblMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Option.
        /// </summary>
        public static string lblMethod {
            get {
                return ResourceManager.GetString("lblMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Amount.
        /// </summary>
        public static string lblMinAmount {
            get {
                return ResourceManager.GetString("lblMinAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum for recharge :.
        /// </summary>
        public static string lblMinRecharge {
            get {
                return ResourceManager.GetString("lblMinRecharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string lblMobile {
            get {
                return ResourceManager.GetString("lblMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Record.
        /// </summary>
        public static string lblMyRecord {
            get {
                return ResourceManager.GetString("lblMyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Referral.
        /// </summary>
        public static string lblMyReferral {
            get {
                return ResourceManager.GetString("lblMyReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Team.
        /// </summary>
        public static string lblMyTeam {
            get {
                return ResourceManager.GetString("lblMyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string lblNameIsRequired {
            get {
                return ResourceManager.GetString("lblNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate.
        /// </summary>
        public static string lblNavigate {
            get {
                return ResourceManager.GetString("lblNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Type.
        /// </summary>
        public static string lblNetworkType {
            get {
                return ResourceManager.GetString("lblNetworkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string lblNew {
            get {
                return ResourceManager.GetString("lblNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required.
        /// </summary>
        public static string lblNewPasswordIsRequired {
            get {
                return ResourceManager.GetString("lblNewPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string lblNewPwd {
            get {
                return ResourceManager.GetString("lblNewPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found.
        /// </summary>
        public static string lblNoRecFound {
            get {
                return ResourceManager.GetString("lblNoRecFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string lblNotAvailable {
            get {
                return ResourceManager.GetString("lblNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Used.
        /// </summary>
        public static string lblNotUsed {
            get {
                return ResourceManager.GetString("lblNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string lblNumber {
            get {
                return ResourceManager.GetString("lblNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 0 return rate.
        /// </summary>
        public static string lblNumber0ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber0ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 1 return rate.
        /// </summary>
        public static string lblNumber1ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber1ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 2 return rate.
        /// </summary>
        public static string lblNumber2ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber2ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 3 return rate.
        /// </summary>
        public static string lblNumber3ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber3ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 4 return rate.
        /// </summary>
        public static string lblNumber4ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber4ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 5 return rate.
        /// </summary>
        public static string lblNumber5ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber5ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 6 return rate.
        /// </summary>
        public static string lblNumber6ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber6ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 7 return rate.
        /// </summary>
        public static string lblNumber7ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber7ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 8 return rate.
        /// </summary>
        public static string lblNumber8ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber8ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 9 return rate.
        /// </summary>
        public static string lblNumber9ReturnRate {
            get {
                return ResourceManager.GetString("lblNumber9ReturnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string lblOK {
            get {
                return ResourceManager.GetString("lblOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open With an App.
        /// </summary>
        public static string lblOpenWithAnApp {
            get {
                return ResourceManager.GetString("lblOpenWithAnApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string lblOrders {
            get {
                return ResourceManager.GetString("lblOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT OF STOCK.
        /// </summary>
        public static string lblOutOfStock {
            get {
                return ResourceManager.GetString("lblOutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity Record.
        /// </summary>
        public static string lblParityRecord {
            get {
                return ResourceManager.GetString("lblParityRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match.
        /// </summary>
        public static string lblPassNotMatch {
            get {
                return ResourceManager.GetString("lblPassNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string lblPasswordIsRequired {
            get {
                return ResourceManager.GetString("lblPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string lblPayment {
            get {
                return ResourceManager.GetString("lblPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Gateway.
        /// </summary>
        public static string lblPaymentGateway {
            get {
                return ResourceManager.GetString("lblPaymentGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Host.
        /// </summary>
        public static string lblPaymentHost {
            get {
                return ResourceManager.GetString("lblPaymentHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Host is Required.
        /// </summary>
        public static string lblPaymentHostIsRequired {
            get {
                return ResourceManager.GetString("lblPaymentHostIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Key.
        /// </summary>
        public static string lblPaymentKey {
            get {
                return ResourceManager.GetString("lblPaymentKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Key is Required.
        /// </summary>
        public static string lblPaymentKeyIsRequired {
            get {
                return ResourceManager.GetString("lblPaymentKeyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout.
        /// </summary>
        public static string lblPayout {
            get {
                return ResourceManager.GetString("lblPayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string lblPending {
            get {
                return ResourceManager.GetString("lblPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Delivery.
        /// </summary>
        public static string lblPendingDelivery {
            get {
                return ResourceManager.GetString("lblPendingDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string lblPeriod {
            get {
                return ResourceManager.GetString("lblPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is required.
        /// </summary>
        public static string lblPhoneIsRequired {
            get {
                return ResourceManager.GetString("lblPhoneIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string lblPhoneNumber {
            get {
                return ResourceManager.GetString("lblPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number is Required.
        /// </summary>
        public static string lblPhoneNumberIsRequired {
            get {
                return ResourceManager.GetString("lblPhoneNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        public static string lblPleaseWait {
            get {
                return ResourceManager.GetString("lblPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string lblProfile {
            get {
                return ResourceManager.GetString("lblProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Guarantee.
        /// </summary>
        public static string lblQualityGuarantee {
            get {
                return ResourceManager.GetString("lblQualityGuarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recharge.
        /// </summary>
        public static string lblRecharge {
            get {
                return ResourceManager.GetString("lblRecharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recharge Amount.
        /// </summary>
        public static string lblRechargeAmount {
            get {
                return ResourceManager.GetString("lblRechargeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recharge Commission.
        /// </summary>
        public static string lblRechargeCommission {
            get {
                return ResourceManager.GetString("lblRechargeCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recharge Time.
        /// </summary>
        public static string lblRechargeTime {
            get {
                return ResourceManager.GetString("lblRechargeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recharge Wallet.
        /// </summary>
        public static string lblRechargeWallet {
            get {
                return ResourceManager.GetString("lblRechargeWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red 0 return rate.
        /// </summary>
        public static string lblRed0Return {
            get {
                return ResourceManager.GetString("lblRed0Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Packet.
        /// </summary>
        public static string lblRedPacket {
            get {
                return ResourceManager.GetString("lblRedPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red return rate.
        /// </summary>
        public static string lblRedReturn {
            get {
                return ResourceManager.GetString("lblRedReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference ID.
        /// </summary>
        public static string lblReferenceID {
            get {
                return ResourceManager.GetString("lblReferenceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referrals.
        /// </summary>
        public static string lblReferrals {
            get {
                return ResourceManager.GetString("lblReferrals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Witdrawal.
        /// </summary>
        public static string lblRefundWdr {
            get {
                return ResourceManager.GetString("lblRefundWdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string lblReject {
            get {
                return ResourceManager.GetString("lblReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string lblRemark {
            get {
                return ResourceManager.GetString("lblRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string lblRememberMe {
            get {
                return ResourceManager.GetString("lblRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string lblResult {
            get {
                return ResourceManager.GetString("lblResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Level.
        /// </summary>
        public static string lblSecondLevel {
            get {
                return ResourceManager.GetString("lblSecondLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Level Commission.
        /// </summary>
        public static string lblSecondLevelCommission {
            get {
                return ResourceManager.GetString("lblSecondLevelCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Bank Card.
        /// </summary>
        public static string lblSelectBankCard {
            get {
                return ResourceManager.GetString("lblSelectBankCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Rate.
        /// </summary>
        public static string lblSell {
            get {
                return ResourceManager.GetString("lblSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Rate is required.
        /// </summary>
        public static string lblSellRateIsRequired {
            get {
                return ResourceManager.GetString("lblSellRateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Fee.
        /// </summary>
        public static string lblServiceFee {
            get {
                return ResourceManager.GetString("lblServiceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped.
        /// </summary>
        public static string lblShipped {
            get {
                return ResourceManager.GetString("lblShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Password.
        /// </summary>
        public static string lblShowPassword {
            get {
                return ResourceManager.GetString("lblShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up now!.
        /// </summary>
        public static string lblSignUpNow {
            get {
                return ResourceManager.GetString("lblSignUpNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOLD OUT.
        /// </summary>
        public static string lblSoldOut {
            get {
                return ResourceManager.GetString("lblSoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Bonus.
        /// </summary>
        public static string lblSponsorBonus {
            get {
                return ResourceManager.GetString("lblSponsorBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string lblStart {
            get {
                return ResourceManager.GetString("lblStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State / Territory.
        /// </summary>
        public static string lblState {
            get {
                return ResourceManager.GetString("lblState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string lblSuccess {
            get {
                return ResourceManager.GetString("lblSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string lblSupport {
            get {
                return ResourceManager.GetString("lblSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Telegram.
        /// </summary>
        public static string lblSupportTelegram {
            get {
                return ResourceManager.GetString("lblSupportTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Level.
        /// </summary>
        public static string lblThirdLevel {
            get {
                return ResourceManager.GetString("lblThirdLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Level Commission.
        /// </summary>
        public static string lblThirdLevelCommission {
            get {
                return ResourceManager.GetString("lblThirdLevelCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string lblTo {
            get {
                return ResourceManager.GetString("lblTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopUp.
        /// </summary>
        public static string lblTopUp {
            get {
                return ResourceManager.GetString("lblTopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Balance.
        /// </summary>
        public static string lblTotalBalance {
            get {
                return ResourceManager.GetString("lblTotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Commission.
        /// </summary>
        public static string lblTotalCommission {
            get {
                return ResourceManager.GetString("lblTotalCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Direct Downline.
        /// </summary>
        public static string lblTotalDirectDownline {
            get {
                return ResourceManager.GetString("lblTotalDirectDownline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Downline.
        /// </summary>
        public static string lblTotalDownline {
            get {
                return ResourceManager.GetString("lblTotalDownline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Downline Bet.
        /// </summary>
        public static string lblTotalDownlineBet {
            get {
                return ResourceManager.GetString("lblTotalDownlineBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Downline Commission.
        /// </summary>
        public static string lblTotalDownlineCommission {
            get {
                return ResourceManager.GetString("lblTotalDownlineCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Downline Win.
        /// </summary>
        public static string lblTotalDownlineWin {
            get {
                return ResourceManager.GetString("lblTotalDownlineWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Interest.
        /// </summary>
        public static string lblTotalInterest {
            get {
                return ResourceManager.GetString("lblTotalInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Recharge.
        /// </summary>
        public static string lblTotalRecharge {
            get {
                return ResourceManager.GetString("lblTotalRecharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Withdrawal.
        /// </summary>
        public static string lblTotalWithdrawal {
            get {
                return ResourceManager.GetString("lblTotalWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string lblTransaction {
            get {
                return ResourceManager.GetString("lblTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        public static string lblTransactionDate {
            get {
                return ResourceManager.GetString("lblTransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tron.
        /// </summary>
        public static string lblTron {
            get {
                return ResourceManager.GetString("lblTron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string lblUpdate {
            get {
                return ResourceManager.GetString("lblUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Successfully.
        /// </summary>
        public static string lblUpdateSuccessfully {
            get {
                return ResourceManager.GetString("lblUpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string lblUsed {
            get {
                return ResourceManager.GetString("lblUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string lblUsernameIsRequired {
            get {
                return ResourceManager.GetString("lblUsernameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exists.
        /// </summary>
        public static string lblUserNotExists {
            get {
                return ResourceManager.GetString("lblUserNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string lblValue {
            get {
                return ResourceManager.GetString("lblValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string lblVerificationCode {
            get {
                return ResourceManager.GetString("lblVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string lblView {
            get {
                return ResourceManager.GetString("lblView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        public static string lblViewAll {
            get {
                return ResourceManager.GetString("lblViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet return rate.
        /// </summary>
        public static string lblVioletReturn {
            get {
                return ResourceManager.GetString("lblVioletReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Address.
        /// </summary>
        public static string lblWalletAddress {
            get {
                return ResourceManager.GetString("lblWalletAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Address is required.
        /// </summary>
        public static string lblWalletAddressIsRequired {
            get {
                return ResourceManager.GetString("lblWalletAddressIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Name.
        /// </summary>
        public static string lblWalletName {
            get {
                return ResourceManager.GetString("lblWalletName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string lblWarning {
            get {
                return ResourceManager.GetString("lblWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Back.
        /// </summary>
        public static string lblWelcomeBack {
            get {
                return ResourceManager.GetString("lblWelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Hot Mall!.
        /// </summary>
        public static string lblWelcomeToMall {
            get {
                return ResourceManager.GetString("lblWelcomeToMall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string lblWin {
            get {
                return ResourceManager.GetString("lblWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win Amount.
        /// </summary>
        public static string lblWinAmount {
            get {
                return ResourceManager.GetString("lblWinAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winning.
        /// </summary>
        public static string lblWinning {
            get {
                return ResourceManager.GetString("lblWinning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal.
        /// </summary>
        public static string lblWithdrawal {
            get {
                return ResourceManager.GetString("lblWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal Amount.
        /// </summary>
        public static string lblWithdrawalAmount {
            get {
                return ResourceManager.GetString("lblWithdrawalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw Host.
        /// </summary>
        public static string lblWithdrawHost {
            get {
                return ResourceManager.GetString("lblWithdrawHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw Host is Required.
        /// </summary>
        public static string lblWithdrawHostIsRequired {
            get {
                return ResourceManager.GetString("lblWithdrawHostIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Control.
        /// </summary>
        public static string mnuAccessControl {
            get {
                return ResourceManager.GetString("mnuAccessControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string mnuAdmin {
            get {
                return ResourceManager.GetString("mnuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Listing.
        /// </summary>
        public static string mnuAdminListing {
            get {
                return ResourceManager.GetString("mnuAdminListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banners.
        /// </summary>
        public static string mnuBanner {
            get {
                return ResourceManager.GetString("mnuBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recharge TopUp.
        /// </summary>
        public static string mnuCashTopUp {
            get {
                return ResourceManager.GetString("mnuCashTopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Wallet Log.
        /// </summary>
        public static string mnuCashWalletLog {
            get {
                return ResourceManager.GetString("mnuCashWalletLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Wallet.
        /// </summary>
        public static string mnuCompanyWallet {
            get {
                return ResourceManager.GetString("mnuCompanyWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Exchange Rate.
        /// </summary>
        public static string mnuCountry {
            get {
                return ResourceManager.GetString("mnuCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Exchange Rate.
        /// </summary>
        public static string mnuCountryExchangeRate {
            get {
                return ResourceManager.GetString("mnuCountryExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Report.
        /// </summary>
        public static string mnuDailyReport {
            get {
                return ResourceManager.GetString("mnuDailyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string mnuGame {
            get {
                return ResourceManager.GetString("mnuGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing.
        /// </summary>
        public static string mnuListing {
            get {
                return ResourceManager.GetString("mnuListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottery Bet Listing.
        /// </summary>
        public static string mnuLotteryBetListing {
            get {
                return ResourceManager.GetString("mnuLotteryBetListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Order.
        /// </summary>
        public static string mnuMyOrder {
            get {
                return ResourceManager.GetString("mnuMyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string mnuProduct {
            get {
                return ResourceManager.GetString("mnuProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recharge Listing.
        /// </summary>
        public static string mnuRechargeListing {
            get {
                return ResourceManager.GetString("mnuRechargeListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Packet.
        /// </summary>
        public static string mnuRedPacket {
            get {
                return ResourceManager.GetString("mnuRedPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Listing.
        /// </summary>
        public static string mnuSessionListing {
            get {
                return ResourceManager.GetString("mnuSessionListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string mnuSettings {
            get {
                return ResourceManager.GetString("mnuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Configuration.
        /// </summary>
        public static string mnuSystemConfiguration {
            get {
                return ResourceManager.GetString("mnuSystemConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string mnuTransaction {
            get {
                return ResourceManager.GetString("mnuTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string mnuUser {
            get {
                return ResourceManager.GetString("mnuUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Listing.
        /// </summary>
        public static string mnuUserListing {
            get {
                return ResourceManager.GetString("mnuUserListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        public static string mnuWallet {
            get {
                return ResourceManager.GetString("mnuWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal Listing.
        /// </summary>
        public static string mnuWithdrawalListing {
            get {
                return ResourceManager.GetString("mnuWithdrawalListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal Logs.
        /// </summary>
        public static string mnuWithdrawalLog {
            get {
                return ResourceManager.GetString("mnuWithdrawalLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You still have balance turn over {0}, before you are allow to do withdrawal.
        /// </summary>
        public static string msgBalanceTurnOverToWithdrwal {
            get {
                return ResourceManager.GetString("msgBalanceTurnOverToWithdrwal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimed successfully.
        /// </summary>
        public static string msgClaimSuccessfully {
            get {
                return ResourceManager.GetString("msgClaimSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        public static string msgConfirmDelete {
            get {
                return ResourceManager.GetString("msgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to approve this transaction ?.
        /// </summary>
        public static string msgConfirmToApprove {
            get {
                return ResourceManager.GetString("msgConfirmToApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this ?.
        /// </summary>
        public static string msgConfirmToDelete {
            get {
                return ResourceManager.GetString("msgConfirmToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reject this transaction ?.
        /// </summary>
        public static string msgConfirmToReject {
            get {
                return ResourceManager.GetString("msgConfirmToReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code Existed.
        /// </summary>
        public static string msgCountryCodeExists {
            get {
                return ResourceManager.GetString("msgCountryCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration must be longer than 60 seconds.
        /// </summary>
        public static string msgDurationMustBeLongerThan60Seconds {
            get {
                return ResourceManager.GetString("msgDurationMustBeLongerThan60Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You balance is insufficient.
        /// </summary>
        public static string msgGameInsufficientFund {
            get {
                return ResourceManager.GetString("msgGameInsufficientFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game session not found.
        /// </summary>
        public static string msgGameSessionNotFound {
            get {
                return ResourceManager.GetString("msgGameSessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re too late to place a bet on this. Please wait for next session.
        /// </summary>
        public static string msgGameTooLateToBet {
            get {
                return ResourceManager.GetString("msgGameTooLateToBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input amount for this red packet.
        /// </summary>
        public static string msgInputAmountRedPacket {
            get {
                return ResourceManager.GetString("msgInputAmountRedPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient wallet balance.
        /// </summary>
        public static string msgInsufficientWalletBalance {
            get {
                return ResourceManager.GetString("msgInsufficientWalletBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Actual name.
        /// </summary>
        public static string msgInvalidActualName {
            get {
                return ResourceManager.GetString("msgInvalidActualName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Amount.
        /// </summary>
        public static string msgInvalidAmount {
            get {
                return ResourceManager.GetString("msgInvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Bank Account.
        /// </summary>
        public static string msgInvalidBankId {
            get {
                return ResourceManager.GetString("msgInvalidBankId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Bank Name.
        /// </summary>
        public static string msgInvalidBankName {
            get {
                return ResourceManager.GetString("msgInvalidBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid From Date.
        /// </summary>
        public static string msgInvalidFromDate {
            get {
                return ResourceManager.GetString("msgInvalidFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IFSC Code.
        /// </summary>
        public static string msgInvalidIFSCCode {
            get {
                return ResourceManager.GetString("msgInvalidIFSCCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login.
        /// </summary>
        public static string msgInvalidLogin {
            get {
                return ResourceManager.GetString("msgInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name.
        /// </summary>
        public static string msgInvalidName {
            get {
                return ResourceManager.GetString("msgInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string msgInvalidPassword {
            get {
                return ResourceManager.GetString("msgInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidPhoneNumber.
        /// </summary>
        public static string msgInvalidPhoneNumber {
            get {
                return ResourceManager.GetString("msgInvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid red packet.
        /// </summary>
        public static string msgInvalidRedPacket {
            get {
                return ResourceManager.GetString("msgInvalidRedPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid referral.
        /// </summary>
        public static string msgInvalidReferral {
            get {
                return ResourceManager.GetString("msgInvalidReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid result number.
        /// </summary>
        public static string msgInvalidResultNumber {
            get {
                return ResourceManager.GetString("msgInvalidResultNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid To Date.
        /// </summary>
        public static string msgInvalidToDate {
            get {
                return ResourceManager.GetString("msgInvalidToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum withdrawal allowed is :.
        /// </summary>
        public static string msgMaxWithdrawalAmount {
            get {
                return ResourceManager.GetString("msgMaxWithdrawalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum withdrawal allowed is :.
        /// </summary>
        public static string msgMinWithdrawalAmount {
            get {
                return ResourceManager.GetString("msgMinWithdrawalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order placed successfully.
        /// </summary>
        public static string msgOrderPlaceSucessfully {
            get {
                return ResourceManager.GetString("msgOrderPlaceSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password do not match.
        /// </summary>
        public static string msgPasswordNotMatch {
            get {
                return ResourceManager.GetString("msgPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You still have pending withdrawal not yet approve.
        /// </summary>
        public static string msgPendingWithdrwawal {
            get {
                return ResourceManager.GetString("msgPendingWithdrwawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is not registered.
        /// </summary>
        public static string msgPhoneIsNotRegistered {
            get {
                return ResourceManager.GetString("msgPhoneIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must be 10 digit.
        /// </summary>
        public static string msgPhoneNumberIndiaMustBe10Digit {
            get {
                return ResourceManager.GetString("msgPhoneNumberIndiaMustBe10Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are required to agree with the rules.
        /// </summary>
        public static string msgPleaseAgreeRules {
            get {
                return ResourceManager.GetString("msgPleaseAgreeRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successfully.
        /// </summary>
        public static string msgSaveSuccessfully {
            get {
                return ResourceManager.GetString("msgSaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expired.
        /// </summary>
        public static string msgSessionExpired {
            get {
                return ResourceManager.GetString("msgSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully sent.
        /// </summary>
        public static string msgSuccesfullySent {
            get {
                return ResourceManager.GetString("msgSuccesfullySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Existed.
        /// </summary>
        public static string msgUserExisted {
            get {
                return ResourceManager.GetString("msgUserExisted", resourceCulture);
            }
        }
    }
}
