USE ColorPrediction
GO

/****** Object:  Table [dbo].[CVD_GAME_SESSION_BET]    Script Date: 16/12/2022 2:33:11 PM ******/
DROP TABLE [dbo].[CVD_GAME_SESSION_BET]
GO

/****** Object:  Table [dbo].[CVD_GAME_SESSION_BET]    Script Date: 16/12/2022 2:33:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CVD_GAME_SESSION_BET](
	[CBET_ID] [int] IDENTITY(1,1) NOT NULL,
	[CGAMESES_ID] INT NOT NULL,
	[CGAME_NUMBER] INT NOT NULL,--55 Green 66 Violet 77 Red
	[CUSR_USERNAME] NVARCHAR(200) NOT NULL,
	[CGAME_AMOUNT] DECIMAL(15,2) NOT NULL,
	[CGAME_WIN_AMOUNT] DECIMAL(15,2) NOT NULL,
	[CBET_DELETIONSTATE] [bit] NOT NULL,
 CONSTRAINT [PK_CVD_GAME_SESSION_BET] PRIMARY KEY CLUSTERED 
(
	[CBET_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


