USE ColorPrediction
GO

/****** Object:  Table [dbo].[CVD_PENDING_JOB]    Script Date: 20/3/2023 11:48:15 AM ******/
DROP TABLE [dbo].[CVD_PENDING_JOB]
GO

/****** Object:  Table [dbo].[CVD_PENDING_JOB]    Script Date: 20/3/2023 11:48:15 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CVD_PENDING_JOB](
	[CJOB_ID] [int] IDENTITY(1,1) NOT NULL,
	[CUSR_USERNAME] [nvarchar](200) NOT NULL,
	[CJOB_AMOUNT] DECIMAL(15,2) NOT NULL,
	[CJOB_CASHNAME] [nvarchar](200) NOT NULL,
	[CJOB_APPOTHER1] [nvarchar](200) NOT NULL,
	[CJOB_APPOTHER2] [nvarchar](200) NOT NULL,
	[CJOB_STATUS] [int] NOT NULL,
	[CJOB_CREATEDON] [datetime] NOT NULL,
 CONSTRAINT [PK_CVD_PENDING_JOB] PRIMARY KEY CLUSTERED 
(
	[CJOB_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


