USE [ColorPrediction]
GO

/****** Object:  Table [dbo].[CVD_MEMBER_BANK]    Script Date: 20/3/2023 3:15:19 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CVD_MEMBER_BANK](
	[CBANK_ID] [int] IDENTITY(1,1) NOT NULL,
	[CUSR_USERNAME] [nvarchar](200) NULL,
	[CBANK_NAME] [nvarchar](300) NOT NULL,
	[CBANK_IFSCCODE] [nvarchar](300) NOT NULL,	
	[CBANK_BANKACCOUNTNAME] [nvarchar](300) NOT NULL,
	[CBANK_BANKACCOUNT] [nvarchar](300) NOT NULL,
	[CBANK_STATE] [nvarchar](300) NOT NULL,
	[CBANK_CITY] [nvarchar](300) NOT NULL,
	[CBANK_ADDRESS] [nvarchar](2000) NOT NULL,
	[CBANK_MOBILE] [nvarchar](300) NOT NULL,
	[CBANK_EMAIL] [nvarchar](300) NOT NULL,	
	[CBANK_CREATEDBY] [nvarchar](100) NOT NULL,
	[CBANK_CREATEDON] [datetime] NOT NULL,	
	[CBANK_DELETIONSTATE] [bit] NOT NULL,
 CONSTRAINT [PK_CVD_MEMBER_BANKS] PRIMARY KEY CLUSTERED 
(
	[CBANK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CVD_MEMBER_BANK] ADD  DEFAULT ('') FOR [CBANK_STATE]
GO

ALTER TABLE [dbo].[CVD_MEMBER_BANK] ADD  DEFAULT ('') FOR [CBANK_EMAIL]
GO


