USE [ColorPrediction]
GO

/****** Object:  Table [dbo].[CVD_PAYMENTINFO]    Script Date: 19/3/2023 8:11:24 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CVD_PAYMENTINFO](
	[CPAYMENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[CUSR_USERNAME] [nvarchar](500) NOT NULL,
	[CPAYMENT_TRANSPAYMENTID] [nvarchar](500) NOT NULL,
	[CPAYMENT_TRANSID] [nvarchar](500) NOT NULL,
	[CPAYMENT_AMOUNT] [decimal](12, 2) NOT NULL,
	[CPAYMENT_ISSUEBANK] [nvarchar](500) NULL,
	[CPAYMENT_TRANSMSG] [nvarchar](500) NULL,
	[CPAYMENT_RETURNCODE] [nvarchar](500) NULL,
	[CPAYMENT_RETURNSIGN] [nvarchar](500) NULL,
	[CPAYMENT_CREATEDON] [datetime] NOT NULL,
 CONSTRAINT [PK_CVD_PAYMENTINFO] PRIMARY KEY CLUSTERED 
(
	[CPAYMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CVD_PAYMENTINFO] ADD  DEFAULT (getdate()) FOR [CPAYMENT_CREATEDON]
GO


