USE [ColorPrediction]
GO

/****** Object:  Table [dbo].[CVD_SYSTEMERROR]    Script Date: 19/3/2023 8:19:55 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CVD_SYSTEMERROR](
	[CERROR_ID] [int] IDENTITY(1,1) NOT NULL,
	[CERROR_INFO] [nvarchar](max) NOT NULL,
	[CERROR_APPOTHER] [nvarchar](200) NULL,
	[CERROR_APPOTHER2] [nvarchar](1000) NULL,
	[CERROR_APPOTHER3] [nvarchar](1000) NULL,
	[CERROR_CREATEDON] [datetime] NOT NULL,
 CONSTRAINT [PK_CVD_SYSTEMERROR] PRIMARY KEY CLUSTERED 
(
	[CERROR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CVD_SYSTEMERROR] ADD  DEFAULT (getdate()) FOR [CERROR_CREATEDON]
GO


