USE ColorPrediction
GO

/****** Object:  Table [dbo].[CVD_GAME]    Script Date: 16/12/2022 2:33:11 PM ******/
DROP TABLE [dbo].[CVD_GAME]
GO

/****** Object:  Table [dbo].[CVD_GAME]    Script Date: 16/12/2022 2:33:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CVD_GAME](
	[CGAME_ID] [int] IDENTITY(1,1) NOT NULL,
	[CGAME_NAME] NVARCHAR(200) NOT NULL,
	[CGAME_STATUS] INT NOT NULL,
	[CGAME_IMAGEPATH] NVARCHAR(1000) NOT NULL,
	[CGAME_TYPE] INT NOT NULL,--0 Beauty 1 Beast
	[CGAME_DURATION_SECONDS] INT NOT NULL,
	[CGAME_NO9_RETURN] DECIMAL(15,2) NOT NULL,
	[CGAME_NO8_RETURN] DECIMAL(15,2) NOT NULL,
	[CGAME_NO7_RETURN] DECIMAL(15,2) NOT NULL,
	[CGAME_NO6_RETURN] DECIMAL(15,2) NOT NULL,
	[CGAME_NO5_RETURN] DECIMAL(15,2) NOT NULL,
	[CGAME_NO4_RETURN] DECIMAL(15,2) NOT NULL,
	[CGAME_NO3_RETURN] DECIMAL(15,2) NOT NULL,
	[CGAME_NO2_RETURN] DECIMAL(15,2) NOT NULL,
	[CGAME_NO1_RETURN] DECIMAL(15,2) NOT NULL,
	[CGAME_NO0_RETURN] DECIMAL(15,2) NOT NULL,
	[CGAME_RED_RETURN] DECIMAL(15,2) NOT NULL,
	[CGAME_VIOLET_RETURN] DECIMAL(15,2) NOT NULL,
	[CGAME_RED0_RETURN] DECIMAL(15,2) NOT NULL,
	[CGAME_GREEN_RETURN] DECIMAL(15,2) NOT NULL,
	[CGAME_GREEN5_RETURN] DECIMAL(15,2) NOT NULL,
	[CGAME_DELETIONSTATE] [bit] NOT NULL,
 CONSTRAINT [PK_CVD_GAME] PRIMARY KEY CLUSTERED 
(
	[CGAME_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


