USE [ColorPrediction]
GO

/****** Object:  Table [dbo].[CVD_PRODUCT]    Script Date: 14/3/2023 6:46:59 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CVD_PRODUCT](
	[CPRO_ID] [int] IDENTITY(1,1) NOT NULL,
	[CPRO_TITLE] [nvarchar](200) NOT NULL,
	[CPRO_IMAGES] [nvarchar](2000) NOT NULL,
	[CPRO_DESC] [nvarchar](max) NULL,
	[CPRO_DESC_ADD] [nvarchar](max) NOT NULL,
	[CPRO_PRICE] [decimal](10, 2) NOT NULL,
	[CPRO_CREATEDBY] [nvarchar](50) NOT NULL,
	[CPRO_CREATEDON] [datetime] NOT NULL,
	[CPRO_DELETIONSTATE] [bit] NOT NULL,
 CONSTRAINT [PK_CVD_PRODUCT] PRIMARY KEY CLUSTERED 
(
	[CPRO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CVD_PRODUCT] ADD  DEFAULT ('SYS') FOR [CPRO_CREATEDBY]
GO

ALTER TABLE [dbo].[CVD_PRODUCT] ADD  DEFAULT (getdate()) FOR [CPRO_CREATEDON]
GO

ALTER TABLE [dbo].[CVD_PRODUCT] ADD  DEFAULT ((0)) FOR [CPRO_DELETIONSTATE]
GO
