USE [ColorPrediction]
GO

/****** Object:  Table [dbo].[CVD_COMPANYWALLET]    Script Date: 26/3/2023 8:34:04 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CVD_COMPANYWALLET](
	[CCOM_ID] [int] IDENTITY(1,1) NOT NULL,
	[CCOM_NAME] [nvarchar](200) NOT NULL,
	[CCOM_NETWORKTYPE] [nvarchar](200) NOT NULL,
	[CCOM_WALLETADDRESS] [nvarchar](200) NOT NULL,	
	[CCOM_CREATEDBY] [nvarchar](200) NOT NULL,
	[CCOM_CREATEDON] [datetime] NOT NULL,
	[CCOM_DELETIONSTATE] [bit] NOT NULL,
 CONSTRAINT [PK_CVD_COMPANYWALLET] PRIMARY KEY CLUSTERED 
(
	[CCOM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CVD_COMPANYWALLET] ADD  DEFAULT ('SYS') FOR [CCOM_CREATEDBY]
GO

ALTER TABLE [dbo].[CVD_COMPANYWALLET] ADD  DEFAULT (getdate()) FOR [CCOM_CREATEDON]
GO

ALTER TABLE [dbo].[CVD_COMPANYWALLET] ADD  DEFAULT ((0)) FOR [CCOM_DELETIONSTATE]
GO
