USE ColorPrediction
GO

/****** Object:  Table [dbo].[CVD_RED_PACKET]    Script Date: 16/12/2022 2:33:11 PM ******/
DROP TABLE [dbo].[CVD_RED_PACKET]
GO

/****** Object:  Table [dbo].[CVD_RED_PACKET]    Script Date: 16/12/2022 2:33:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CVD_RED_PACKET](
	[CREDP_ID] [int] IDENTITY(1,1) NOT NULL,
	[CREDP_REFERENCE_ID] [nvarchar](200) NOT NULL,
	[CREDP_AGENT] [nvarchar](200) NOT NULL,
	[CUSR_USERNAME] [nvarchar](2000) NOT NULL,
	[CREDP_AMOUNT] DECIMAL(15,2) NOT NULL,
	[CREDP_CREATEDON] [datetime] NOT NULL,
	[CREDP_CLAIMEDON] [datetime] NULL,
	[CREDP_STATUS] INT NOT NULL,
	[CREDP_DELETIONSTATE] [bit] NOT NULL,
 CONSTRAINT [PK_CVD_RED_PACKET] PRIMARY KEY CLUSTERED 
(
	[CREDP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


