USE [ColorPrediction]
GO

/****** Object:  Table [dbo].[CVD_BANK]    Script Date: 19/3/2023 2:04:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CVD_BANK](
	[CBANK_ID] [int] IDENTITY(1,1) NOT NULL,
	[CCOUNTRY_CODE] [nvarchar](100) NOT NULL,
	[CBANK_CODE] [varchar](100) NOT NULL,
	[CBANK_NAME] [varchar](100) NULL,
	[CBANK_DELETIONSTATE] [bit] NOT NULL,
 CONSTRAINT [PK_CVD_BANK] PRIMARY KEY CLUSTERED 
(
	[CBANK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CVD_BANK] ADD  DEFAULT ('0') FOR [CBANK_DELETIONSTATE]
GO


