USE [ColorPrediction]
GO

/****** Object:  Table [dbo].[CVD_BANNER]    Script Date: 18/3/2023 8:57:28 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CVD_BANNER](
	[CBANNER_ID] [int] IDENTITY(1,1) NOT NULL,
	[CBANNER_TITLE] [nvarchar](200) NOT NULL,
	[CBANNER_IMAGES] [nvarchar](2000) NOT NULL,
	[CBANNER_CREATEDBY] [nvarchar](50) NOT NULL,
	[CBANNER_CREATEDON] [datetime] NOT NULL,
	[CBANNER_DELETIONSTATE] [bit] NOT NULL,
 CONSTRAINT [PK_CVD_BANNER] PRIMARY KEY CLUSTERED 
(
	[CBANNER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CVD_BANNER] ADD  DEFAULT ('SYS') FOR [CBANNER_CREATEDBY]
GO

ALTER TABLE [dbo].[CVD_BANNER] ADD  DEFAULT (getdate()) FOR [CBANNER_CREATEDON]
GO

ALTER TABLE [dbo].[CVD_BANNER] ADD  DEFAULT ((0)) FOR [CBANNER_DELETIONSTATE]
GO


