USE [ColorPrediction]
GO

/****** Object:  Table [dbo].[CVD_DAILYTRANS]    Script Date: 23/3/2023 10:11:08 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CVD_DAILYTRANS](
	[CDAIL_ID] [int] IDENTITY(1,1) NOT NULL,
	[CDAIL_TRANDATE] [datetime] NOT NULL,
	[CDAIL_RECHARGE] [decimal](15, 2) NULL,
	[CDAIL_BET] [decimal](15, 2) NULL,
	[CDAIL_WIN] [decimal](15, 2) NULL,
	[CDAIL_WITHDRAW] [decimal](15, 2) NULL
 CONSTRAINT [PK_CVD_DAILYTRANS] PRIMARY KEY CLUSTERED 
(
	[CDAIL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO